#define MAX_BINARY_LENGTH 3
#define ANALYZE_BUF_INIT_SIZE 5
#define ANALYZE_BUF_ALLOCATE_SIZE 30
#define LABEL_BUF_INIT_SIZE 1
#define LABEL_BUF_ALLOCATE_SIZE 10
#define MSG_LENGTH 256
#define MAX_ARGS 3